from declarations import *

EN_GPIO = {
    "1": gpio_EN_P1,
    "2": gpio_EN_P2,
    "3": gpio_EN_P3,
    "4": gpio_EN_P4,
    "5": gpio_EN_P5
}

for gpio in EN_GPIO.values():
    gpio.write(0)

print("Enter peripheral number (1-5) to activate for 3s, or q to quit")
try:
    while True:
        inp = input("> ").strip()
        if inp == "q":
            break
        if inp == "B+":
            print("Turning on BACKUP EN")
            gpio_nBACKUP_EN.write(0)
            continue
        if inp == "B-":
            print("Turning off BACKUP EN")
            gpio_nBACKUP_EN.write(1)
            continue
        if inp in EN_GPIO:
            print(f"Activating P{inp} for 3s...")
            EN_GPIO[inp].write(1)
            time.sleep(3)
            EN_GPIO[inp].write(0)
            print(f"P{inp} deactivated")
        else:
            print("Invalid. Enter 1-5 or q")
except KeyboardInterrupt:
    pass
finally:
    for gpio in EN_GPIO.values():
        gpio.write(0)



dtoverlay=rk3568-i2c3-m0
dtoverlay=rk3568-spi3-m1-cs0-spidev
dtoverlay=rk3568-uart7-m1




## /boot/extlinux/extlinux.conf
##
## IMPORTANT WARNING
##
## The configuration of this file is generated automatically.
## Do not edit this file manually, use: u-boot-update

default l0
menu title U-Boot menu
prompt 1
timeout 10


label l0
        menu label Debian GNU/Linux 11 (bullseye) 5.10.160-18-rk356x
        linux /boot/vmlinuz-5.10.160-18-rk356x
        initrd /boot/initrd.img-5.10.160-18-rk356x
        fdtdir /usr/lib/linux-image-5.10.160-18-rk356x/
        fdtoverlays  /boot/dtbo/rk3568-i2c3-m0.dtbo /boot/dtbo/rk3568-spi3-m1-cs0-spidev.dtbo /boot/dtbo/rk3568-uart7-m1.dtbo
        append root=UUID=e7612ded-fff7-4765-bc58-532d87cc48d0 loglevel=4 rw earlycon consoleblank=0 console=tty0 console=ttyAML0,115200n8 console=ttyS0,1500000n8 coherent_pool=2M irqchip.gicv3_pseudo_nmi=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1 timeout=0

label l0r
        menu label Debian GNU/Linux 11 (bullseye) 5.10.160-18-rk356x (rescue target)
        linux /boot/vmlinuz-5.10.160-18-rk356x
        initrd /boot/initrd.img-5.10.160-18-rk356x
        fdtdir /usr/lib/linux-image-5.10.160-18-rk356x/
        fdtoverlays  /boot/dtbo/rk3568-i2c3-m0.dtbo /boot/dtbo/rk3568-spi3-m1-cs0-spidev.dtbo /boot/dtbo/rk3568-uart7-m1.dtbo
        append root=UUID=e7612ded-fff7-4765-bc58-532d87cc48d0 loglevel=4 rw earlycon consoleblank=0 console=tty0 console=ttyAML0,115200n8 console=ttyS0,1500000n8 coherent_pool=2M irqchip.gicv3_pseudo_nmi=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1 timeout=0 single


sudo cp rk3568-uart7-m1.dtbo.disabled rk3568-uart7-m1.dtbo
sudo cp rk3568-i2c3-m0.dtbo.disabled rk3568-i2c3-m0.dtbo
sudo cp rk3568-spi3-m0-cs0-spidev.dtbo.disabled rk3568-spi3-m0-cs0-spidev.dtbo


fdtoverlays  /boot/dtbo/rk3568-i2c3-m0.dtbo /boot/dtbo/rk3568-spi3-m1-cs0-spidev.dtbo /boot/dtbo/rk3568-uart7-m1.dtbo
