class MessagePack:
    def __init__(self, message='0' * 311):
         self.package_count = int(message[0:8], 2)
         self.timestamp = int(message[8:40], 2)
         self.voltage_28V = int(message[40:48], 2)
         self.voltage_5V = int(message[48:56], 2)
         self.voltage_12V = int(message[56:64], 2)
         self.voltage_24V = int(message[64:72], 2)
         self.current_5V = int(message[72:88], 2)
         self.current_12V = int(message[88:104], 2)
         self.current_24V = int(message[104:120], 2)
         self.ebox_temp = int(message[120:129], 2)
         self.pressure = int(message[129:145], 2)
         self.imu_mag_x = int(message[145:153], 2)
         self.imu_mag_y = int(message[153:161], 2)
         self.imu_mag_z = int(message[161:169], 2)
         self.imu_acc_x = int(message[169:177], 2)
         self.imu_acc_y = int(message[177:185], 2)
         self.imu_acc_z = int(message[185:193], 2)
         self.heater_1_status = int(message[193:196], 2)
         self.heater_2_status = int(message[196:199], 2)
         self.heater_3_status = int(message[199:202], 2)
         self.heater_4_status = int(message[202:205], 2)
         self.heater_5_status = int(message[205:208], 2)
         self.heater_6_status = int(message[208:211], 2)
         self.temp_1_status = int(message[211:220], 2)
         self.temp_2_status = int(message[220:229], 2)
         self.temp_3_status = int(message[229:238], 2)
         self.temp_4_status = int(message[238:247], 2)
         self.temp_5_status = int(message[247:256], 2)
         self.temp_6_status = int(message[256:265], 2)
         self.burn_wire_1_status = int(message[265:268], 2)
         self.burn_wire_2_status = int(message[268:271], 2)
         self.current_limiting_status = int(message[271:274], 2)
         self.rpi_1_status = int(message[274:277], 2)
         self.rpi_2_status = int(message[277:280], 2)
         self.rpi_3_status = int(message[280:283], 2)
         self.rpi_4_status = int(message[283:286], 2)
         self.motor_speed = int(message[286:302], 2)
         self.recording_mode_flag = int(message[302:305], 2)
         self.deployment_mode_flag = int(message[305:308], 2)
         self.auto_mode_flag = int(message[308:311], 2)

    def generateString(self):
        bits = [
           "package_count=",f'{self.package_count}',
           ",timestamp=",f'{self.timestamp}',
           ",voltage_28V=",f'{self.voltage_28V}',
           ",voltage_5V=",f'{self.voltage_5V}',
            ",voltage_12V=",f'{self.voltage_12V}',
            ",voltage_24V=",f'{self.voltage_24V}',
            ",current_5V=",f'{self.current_5V}',
            ",current_12V=",f'{self.current_12V}',
            ",current_24V=",f'{self.current_24V}',
            ",ebox_temp=",f'{self.ebox_temp}',
            ",pressure=",f'{self.pressure}',
            ",imu_mag_x=",f'{self.imu_mag_x}',
            ",imu_mag_y=",f'{self.imu_mag_y}',
            ",imu_mag_z=",f'{self.imu_mag_z}',
            ",imu_acc_x=",f'{self.imu_acc_x}',
            ",imu_acc_y=",f'{self.imu_acc_y}',
            ",imu_acc_z=",f'{self.imu_acc_z}',
            ",heater_1_status=",f'{self.heater_1_status}',
            ",heater_2_status=",f'{self.heater_2_status}',
            ",heater_3_status=",f'{self.heater_3_status}',
            ",heater_4_status=",f'{self.heater_4_status}',
            ",heater_5_status=",f'{self.heater_5_status}',
            ",heater_6_status=",f'{self.heater_6_status}',
            ",temp_1_status=",f'{self.temp_1_status}',
            ",temp_2_status=",f'{self.temp_2_status}',
            ",temp_3_status=",f'{self.temp_3_status}',
            ",temp_4_status=",f'{self.temp_4_status}',
            ",temp_5_status=",f'{self.temp_5_status}',
            ",temp_6_status=",f'{self.temp_6_status}',
            ",burn_wire_1_status=",f'{self.burn_wire_1_status}',
            ",burn_wire_2_status=",f'{self.burn_wire_2_status}',
            ",current_limiting_status=",f'{self.current_limiting_status}',
            ",rpi_1_status=",f'{self.rpi_1_status}',
            ",rpi_2_status=",f'{self.rpi_2_status}',
            ",rpi_3_status=",f'{self.rpi_3_status}',
            ",rpi_4_status=",f'{self.rpi_4_status}',
            ",motor_speed=",f'{self.motor_speed}',
            ",recording_mode_flag=",f'{self.recording_mode_flag}',
            ",deployment_mode_flag=",f'{self.deployment_mode_flag}',
            ",auto_mode_flag=",f'{self.auto_mode_flag}',
        ]
        return ''.join(bits)
